### ISSUE TITLE
some question about Edge Loss Reinforced？

### ISSUE THREAD

**Issue by qaqzzz** [liushuo2018/ERN#3]
Hi，Liu

    I'm a graduate student of Shanghai university. 
    I have read your paper about the part of Edge Loss Reinforced. That's a fascinating idea. 
    But I can't find the code about Edge Loss in this git. 
    I want to know, how do you get the edge coordinate and compute it.Is there a simple method?

Best wish to You!

Li

**Comment by liushuo2018** [comment]
Hi, 
    This implementation of ERN is based of Caffe, so you need prepare the edge GT data firstly, and then add corresponding [data layer](https://github.com/liushuo2018/ERN/blob/57c6de992bf5fd43acc8947312b66d621c909a29/VH_ERN/train_ern.prototxt#L59) and [loss layer](https://github.com/liushuo2018/ERN/blob/57c6de992bf5fd43acc8947312b66d621c909a29/VH_ERN/train_ern.prototxt#L2730) in the "training.prototxt".
